Tc 2063 update gem
TerraCycle/spree_print_invoice pull request #1
Opened 2020-02-10 09:09 UTC by ivan-sheremeta

2020-02-11 08:51 UTC, adamFoldvari approved these changes

2020-02-11 09:51 UTC, erik-terracycle requested changes
I suggest using decorators as we did in all the other gems we forked(https://guides.solidus.io/developers/customizations/decorators.html) or if you want to override the Spree::Order class, then move this under overrides and rename the file.

2020-02-11 12:44 UTC, AHolcsik approved these changes

2020-02-12 08:59 UTC, VasiliyMaksymov approved these changes

2020-02-12 09:45 UTC, erik-terracycle approved these changes

2020-02-12 09:54 UTC, SkayHUN approved these changes

2020-02-14 08:24 UTC, merged