[TC-2138] fix sidebar
TerraCycle/spree_print_invoice pull request #2
Opened 2020-02-27 13:21 UTC by adamFoldvari

2020-02-27 13:22 UTC, storhet approved these changes

2020-02-27 16:01 UTC, storhet requested changes
Just found one more style issue related to the Documents
https://puu.sh/Ff3wJ/b8c426cef1.png

2020-02-28 08:24 UTC, adamFoldvari commented
> Just found one more style issue related to the Documents
> https://puu.sh/Ff3wJ/b8c426cef1.png

fixed

2020-02-28 08:41 UTC, storhet approved these changes

2020-02-28 10:45 UTC, merged